/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author PW
 */
public class AreaGestor extends javax.swing.JFrame {

    /**
     * Creates new form AreaGestor
     */
    public AreaGestor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mOrdensServico = new javax.swing.JMenu();
        miCriarOrdensServico = new javax.swing.JMenuItem();
        miPesquisarOrdens = new javax.swing.JMenuItem();
        mContentores = new javax.swing.JMenu();
        miCriarContentor = new javax.swing.JMenuItem();
        miListarContentores = new javax.swing.JMenuItem();
        mParquesContentores = new javax.swing.JMenu();
        miListarParques = new javax.swing.JMenuItem();
        miPesquisarParques = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Área de Gestor");
        setPreferredSize(new java.awt.Dimension(640, 420));
        getContentPane().setLayout(null);

        jButton1.setText("Sair");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(500, 255, 80, 30);

        jButton2.setText("Voltar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(500, 295, 80, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/ECOPONTOS.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 670, 350);

        mOrdensServico.setText("Ordens de Serviço");
        mOrdensServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mOrdensServicoActionPerformed(evt);
            }
        });

        miCriarOrdensServico.setText("Criar Ordens de Serviço");
        miCriarOrdensServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCriarOrdensServicoActionPerformed(evt);
            }
        });
        mOrdensServico.add(miCriarOrdensServico);

        miPesquisarOrdens.setText("Pesquisar");
        mOrdensServico.add(miPesquisarOrdens);

        jMenuBar1.add(mOrdensServico);

        mContentores.setText("Contentores");

        miCriarContentor.setText("Criar Contentor");
        miCriarContentor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCriarContentorActionPerformed(evt);
            }
        });
        mContentores.add(miCriarContentor);

        miListarContentores.setText("Listar Contentores");
        miListarContentores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miListarContentoresActionPerformed(evt);
            }
        });
        mContentores.add(miListarContentores);

        jMenuBar1.add(mContentores);

        mParquesContentores.setText("Parques de Contentores");

        miListarParques.setText("Listar Parques");
        mParquesContentores.add(miListarParques);

        miPesquisarParques.setText("Pesquisar");
        mParquesContentores.add(miPesquisarParques);

        jMenuBar1.add(mParquesContentores);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miListarContentoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miListarContentoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miListarContentoresActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new LoginUtilizador().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void mOrdensServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mOrdensServicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mOrdensServicoActionPerformed

    private void miCriarOrdensServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCriarOrdensServicoActionPerformed
        // TODO add your handling code here:
        new CriarOrdensServico().setVisible(true);
        dispose();
    }//GEN-LAST:event_miCriarOrdensServicoActionPerformed

    private void miCriarContentorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCriarContentorActionPerformed
        // TODO add your handling code here:
        new CriarContentor().setVisible(true);
        dispose();
    }//GEN-LAST:event_miCriarContentorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AreaGestor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AreaGestor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AreaGestor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AreaGestor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AreaGestor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mContentores;
    private javax.swing.JMenu mOrdensServico;
    private javax.swing.JMenu mParquesContentores;
    private javax.swing.JMenuItem miCriarContentor;
    private javax.swing.JMenuItem miCriarOrdensServico;
    private javax.swing.JMenuItem miListarContentores;
    private javax.swing.JMenuItem miListarParques;
    private javax.swing.JMenuItem miPesquisarOrdens;
    private javax.swing.JMenuItem miPesquisarParques;
    // End of variables declaration//GEN-END:variables
}
