/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BLL.Repositorio;
import BLL.Ficheiro;
import BLL.Gestor;
import BLL.Equipa;
import BLL.Municipio;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JFrame;

/**
 *
 * @author PW
 */
public class CriarUtilizador extends javax.swing.JFrame {

    /**
     * Creates new form CriarUtilizador
     */
    public CriarUtilizador() {
        initComponents();
        //Ficheiro.desserializar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtNif = new javax.swing.JTextField();
        txtNCC = new javax.swing.JTextField();
        txtTelefone = new javax.swing.JTextField();
        txtMorada = new javax.swing.JTextField();
        txtLocalidade = new javax.swing.JTextField();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        bCriar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jcTipoUtilizador = new javax.swing.JComboBox<>();
        bVoltar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Criar Utilizador");
        setMinimumSize(new java.awt.Dimension(650, 500));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setText("Nome:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 28, 38, 16);

        jLabel2.setText("Nº CC:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 154, 39, 16);

        jLabel3.setText("NIF:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 91, 24, 16);

        jLabel4.setText("Telefone:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 217, 55, 16);

        jLabel5.setText("Morada:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 280, 48, 16);

        jLabel6.setText("Localidade:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 343, 65, 16);

        jLabel7.setText("Username:");
        jLabel7.setOpaque(true);
        getContentPane().add(jLabel7);
        jLabel7.setBounds(370, 70, 63, 16);

        jLabel8.setText("Password:");
        jLabel8.setOpaque(true);
        getContentPane().add(jLabel8);
        jLabel8.setBounds(370, 140, 60, 16);
        getContentPane().add(txtNome);
        txtNome.setBounds(30, 51, 265, 22);
        getContentPane().add(txtNif);
        txtNif.setBounds(30, 114, 265, 22);

        txtNCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNCCActionPerformed(evt);
            }
        });
        getContentPane().add(txtNCC);
        txtNCC.setBounds(30, 177, 265, 22);
        getContentPane().add(txtTelefone);
        txtTelefone.setBounds(30, 240, 265, 22);
        getContentPane().add(txtMorada);
        txtMorada.setBounds(30, 303, 265, 22);
        getContentPane().add(txtLocalidade);
        txtLocalidade.setBounds(30, 366, 265, 22);
        getContentPane().add(txtUsername);
        txtUsername.setBounds(370, 90, 230, 22);
        getContentPane().add(txtPassword);
        txtPassword.setBounds(370, 160, 230, 22);

        bCriar.setText("Criar");
        bCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCriarActionPerformed(evt);
            }
        });
        getContentPane().add(bCriar);
        bCriar.setBounds(540, 370, 77, 25);
        getContentPane().add(jLabel10);
        jLabel10.setBounds(445, 303, 0, 0);

        jcTipoUtilizador.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gestor", "Equipa", "Municipio" }));
        getContentPane().add(jcTipoUtilizador);
        jcTipoUtilizador.setBounds(400, 200, 180, 22);

        bVoltar.setText("Voltar");
        bVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(bVoltar);
        bVoltar.setBounds(400, 370, 67, 25);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/administrador.jpg"))); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(0, 0, 640, 520);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNCCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNCCActionPerformed

    private void bCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCriarActionPerformed
        // TODO add your handling code here:
        
        
        String tipoUtilizador = ((String)this.jcTipoUtilizador.getSelectedItem());
        
        //Equipa
        if(tipoUtilizador.equals("Equipa")){
       
        Equipa equipa = new Equipa();
        
        equipa.setNome(txtNome.getText());
        
        int nCC = Integer.valueOf(txtNCC.getText());
        equipa.setnCC(nCC);
        
        
        int nif = Integer.valueOf(txtNif.getText());
        equipa.setNif(nif);
        
        int telef = Integer.valueOf(txtTelefone.getText());
        equipa.setTelefone(telef);
        
        equipa.setMorada(txtMorada.getText());
        
        equipa.setLocalidade(txtLocalidade.getText());
        
        equipa.setUsername(txtUsername.getText());
        
        equipa.setPassword(txtPassword.getText());
        
            try {
                Ficheiro.getRepo().addEquipa(equipa);
            } catch (Exception ex) {
                Logger.getLogger(CriarUtilizador.class.getName()).log(Level.SEVERE, null, ex);
                
            }
        Ficheiro.serializar("Repositorio.dat");
        JOptionPane.showMessageDialog(null, "Registado com sucesso!");
        }
        new AreaAdministrador().setVisible(true);
        dispose();
        
        
        //Gestor
        if(tipoUtilizador.equals("Gestor")){
       
        Gestor gestor = new Gestor();
        
        gestor.setNome(txtNome.getText());
        
        int nCC = Integer.valueOf(txtNCC.getText());
        gestor.setnCC(nCC);
        
        
        int nif = Integer.valueOf(txtNif.getText());
        gestor.setNif(nif);
        
        int telef = Integer.valueOf(txtTelefone.getText());
        gestor.setTelefone(telef);
        
        gestor.setMorada(txtMorada.getText());
        
        gestor.setLocalidade(txtLocalidade.getText());
        
        gestor.setUsername(txtUsername.getText());
        
        gestor.setPassword(txtPassword.getText());
        
            try {
                Ficheiro.getRepo().addGestor(gestor);
            } catch (Exception ex) {
                Logger.getLogger(CriarUtilizador.class.getName()).log(Level.SEVERE, null, ex);
                
            }
        Ficheiro.serializar("Repositorio.dat");
        JOptionPane.showMessageDialog(null, "Registado com sucesso!");
        }
        new AreaAdministrador().setVisible(true);
        dispose();
        
        
        //Municipio
        if(tipoUtilizador.equals("Municipio")){
       
        Municipio municipio = new Municipio();
        
        municipio.setNome(txtNome.getText());
        
        int nCC = Integer.valueOf(txtNCC.getText());
        municipio.setnCC(nCC);
        
        
        int nif = Integer.valueOf(txtNif.getText());
        municipio.setNif(nif);
        
        int telef = Integer.valueOf(txtTelefone.getText());
        municipio.setTelefone(telef);
        
        municipio.setMorada(txtMorada.getText());
        
        municipio.setLocalidade(txtLocalidade.getText());
        
        municipio.setUsername(txtUsername.getText());
        
        municipio.setPassword(txtPassword.getText());
        
            try {
                Ficheiro.getRepo().addMunicipio(municipio);
            } catch (Exception ex) {
                Logger.getLogger(CriarUtilizador.class.getName()).log(Level.SEVERE, null, ex);
                
            }
        Ficheiro.serializar("Repositorio.dat");
        JOptionPane.showMessageDialog(null, "Registado com sucesso!");
        }
        new AreaAdministrador().setVisible(true);
        dispose();
        
    }//GEN-LAST:event_bCriarActionPerformed

    private void bVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVoltarActionPerformed
        // TODO add your handling code here:
        
        new AreaAdministrador().setVisible(true);
        dispose();
    }//GEN-LAST:event_bVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CriarUtilizador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CriarUtilizador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CriarUtilizador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CriarUtilizador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CriarUtilizador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCriar;
    private javax.swing.JButton bVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JComboBox<String> jcTipoUtilizador;
    private javax.swing.JTextField txtLocalidade;
    private javax.swing.JTextField txtMorada;
    private javax.swing.JTextField txtNCC;
    private javax.swing.JTextField txtNif;
    private javax.swing.JTextField txtNome;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtTelefone;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
