/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BLL.Ficheiro;
import BLL.Trabalhadores;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author PW
 */
public class CriarTrabalhador extends javax.swing.JFrame {

    /**
     * Creates new form CriarTrabalhador
     */
    public CriarTrabalhador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtNif = new javax.swing.JTextField();
        txtnSegSocial = new javax.swing.JTextField();
        txtContacto = new javax.swing.JTextField();
        txtSalario = new javax.swing.JTextField();
        bCriar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        jTextField4.setText("jTextField4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Criar Trabalhador");
        setPreferredSize(new java.awt.Dimension(500, 525));
        getContentPane().setLayout(null);

        jLabel1.setText("Nome:");
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(46, 38, 38, 16);

        jLabel2.setText("NIF:");
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(46, 101, 24, 16);

        jLabel4.setText("Nº Segurança Social:");
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(46, 164, 122, 16);

        jLabel5.setText("Contacto:");
        jLabel5.setOpaque(true);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(46, 227, 55, 16);

        jLabel6.setText("Salário:");
        jLabel6.setOpaque(true);
        getContentPane().add(jLabel6);
        jLabel6.setBounds(46, 290, 45, 16);
        getContentPane().add(txtNome);
        txtNome.setBounds(46, 61, 333, 22);

        txtNif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNifActionPerformed(evt);
            }
        });
        getContentPane().add(txtNif);
        txtNif.setBounds(46, 124, 333, 22);
        getContentPane().add(txtnSegSocial);
        txtnSegSocial.setBounds(46, 187, 333, 22);
        getContentPane().add(txtContacto);
        txtContacto.setBounds(46, 250, 333, 22);
        getContentPane().add(txtSalario);
        txtSalario.setBounds(46, 313, 333, 22);

        bCriar.setText("Criar");
        bCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCriarActionPerformed(evt);
            }
        });
        getContentPane().add(bCriar);
        bCriar.setBounds(330, 410, 100, 30);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Municipio.png"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 550, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNifActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNifActionPerformed

    private void bCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCriarActionPerformed
        // TODO add your handling code here:
        Trabalhadores trabalhadores = new Trabalhadores();
        
        trabalhadores.setNome(txtNome.getText());
        
        int nifTrabalhador = Integer.valueOf(txtNif.getText());
        trabalhadores.setNifTrabalhador(nifTrabalhador);
        
            try {
                Ficheiro.getRepo().addTrabalhador(trabalhadores);
            } catch (Exception ex) {
                Logger.getLogger(CriarTiposResiduos.class.getName()).log(Level.SEVERE, null, ex);
                
           }
        Ficheiro.serializar("Repositorio.dat");
        JOptionPane.showMessageDialog(null, "Registado com sucesso!");
        
        new AreaMunicipio().setVisible(true);
        dispose();
        
    }//GEN-LAST:event_bCriarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CriarTrabalhador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CriarTrabalhador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CriarTrabalhador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CriarTrabalhador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CriarTrabalhador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCriar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField txtContacto;
    private javax.swing.JTextField txtNif;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtSalario;
    private javax.swing.JTextField txtnSegSocial;
    // End of variables declaration//GEN-END:variables
}
