/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import BLL.Ficheiro;
import BLL.Trabalhadores;
import java.util.Iterator;
import javax.swing.JOptionPane;

/**
 *
 * @author PW
 */
public class RemoverTrabalhador extends javax.swing.JFrame {

    private Iterator<Integer> trabalhadores;

    /**
     * Creates new form RemoverTrabalhador
     */
    public RemoverTrabalhador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtNif = new javax.swing.JTextField();
        txtnSegSocial = new javax.swing.JTextField();
        txtContacto = new javax.swing.JTextField();
        txtSalario = new javax.swing.JTextField();
        bRemover = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Remover Trabalhador");
        setPreferredSize(new java.awt.Dimension(500, 525));
        getContentPane().setLayout(null);

        jLabel1.setText("Nome:");
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(48, 24, 38, 16);

        jLabel2.setText("NIF:");
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(48, 87, 24, 16);

        jLabel3.setText("Nº Segurança Social:");
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(48, 150, 122, 16);

        jLabel4.setText("Contacto:");
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(48, 213, 55, 16);

        jLabel5.setText("Salário:");
        jLabel5.setOpaque(true);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(48, 276, 45, 16);
        getContentPane().add(txtNome);
        txtNome.setBounds(48, 47, 377, 22);
        getContentPane().add(txtNif);
        txtNif.setBounds(48, 110, 377, 22);
        getContentPane().add(txtnSegSocial);
        txtnSegSocial.setBounds(48, 173, 377, 22);
        getContentPane().add(txtContacto);
        txtContacto.setBounds(48, 236, 377, 22);
        getContentPane().add(txtSalario);
        txtSalario.setBounds(48, 299, 377, 22);

        bRemover.setText("Remover");
        bRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRemoverActionPerformed(evt);
            }
        });
        getContentPane().add(bRemover);
        bRemover.setBounds(380, 410, 89, 33);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Municipio.png"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, -10, 570, 520);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRemoverActionPerformed
        // TODO add your handling code here:
        Trabalhadores trabalhadores = new Trabalhadores();
        
        for(int i = 0; i < trabalhadores.size(); i++){
            Trabalhadores tb = trabalhadores.get(i);
        
        
            if(tb.getNome().equals(txtNome.getText())){
                trabalhadores.remove(tb);
                break;
            }    
        }
        Ficheiro.serializar("Repositorio.dat");
        JOptionPane.showMessageDialog(null, "Removido com sucesso!");
        
        new AreaMunicipio().setVisible(true);
        dispose();
    }//GEN-LAST:event_bRemoverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RemoverTrabalhador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RemoverTrabalhador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RemoverTrabalhador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RemoverTrabalhador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RemoverTrabalhador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bRemover;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtContacto;
    private javax.swing.JTextField txtNif;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtSalario;
    private javax.swing.JTextField txtnSegSocial;
    // End of variables declaration//GEN-END:variables
}
